### ISSUE TITLE
[Project] Code Refactoring & Deployment Tool

### ISSUE THREAD

**Issue by sunziping2016** [tillycode/homelab#162]
## TODOs

- [x] migrate desktop
- [x] migrate desktop profiles and home-manger modules
- [x] migrate all services (profiles)
- [x] reinstall all machines
- [ ] ~migrate to colmena~

**Updates**

Colmena was once broken after a recent upgrade of nix. The `makeHive` seems not as intuitive as deploy-rs. So I decided to kept using deploy-rs
